apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "topic-operator.fullname" . }}
  labels:
    app: {{ include "topic-operator.name" . }}
    chart: {{ include "topic-operator.chart" . }}
    component: kafka-service-account
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
