apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "topic-operator.fullname" . }}
  labels:
    app: {{ include "topic-operator.name" . }}
    chart: {{ include "topic-operator.chart" . }}
    component: topic-operator-role-binding
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ include "topic-operator.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "topic-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
