{{- if .Values.saslEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "topic-operator.fullname" . }}-secret
  labels:
    app: {{ include "topic-operator.name" . }}
    chart: {{ include "topic-operator.chart" . }}
    component: deployment
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  client_secret: {{ randAlphaNum 36 | b64enc | quote }}
{{- end }}
