apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
    chart: kafka-0.1.0
    heritage: Tiller
    pod: POD_NAME
    release: HELM_NAME
  name: NODE_PORT_NAME
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: external-broker
    nodePort: NODE_PORT_VALUE
    port: 19092
    protocol: TCP
    targetPort: NODE_PORT_VALUE
  selector:
    app: kafka
    release: HELM_NAME
    statefulset.kubernetes.io/pod-name: POD_NAME
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
