{{- if .Values.saslEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cp-kafka.fullname" . }}-secret
  labels:
    app: {{ template "cp-kafka.name" . }}
    chart: {{ template "cp-kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  client_secret: {{ randAlphaNum 36 | b64enc | quote }}
{{- end }}
