{{- if .Values.persistence.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.persistence.dataDirStorageClass }}
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: thin
  fstype: ext3
reclaimPolicy: Delete
{{- end }}
